'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace n01366094_assignment1
    
    Partial Public Class WebForm1
        
        '''<summary>
        '''busIncidentForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents busIncidentForm As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''repoterFName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repoterFName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''reporterLName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reporterLName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''reporterAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reporterAge As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''tourOrigin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tourOrigin As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''tourDestination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tourDestination As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''totalPassengers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalPassengers As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''injuredPassengerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents injuredPassengerNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''driverFName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents driverFName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''driverLName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents driverLName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''driverPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents driverPhone As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''driverAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents driverAddress As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''driverProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents driverProvince As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''licensePlate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents licensePlate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''incidentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents incidentDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''incidentTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents incidentTime As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''areaLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents areaLocation As Global.System.Web.UI.WebControls.RadioButtonList
    End Class
End Namespace
